-- MySQL Script generated by MySQL Workbench
-- Fri Nov 12 17:52:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street_name` VARCHAR(45) NOT NULL,
  `house_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_address`),
  UNIQUE INDEX `id_address_UNIQUE` (`id_address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `id_address` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`id_person`),
  UNIQUE INDEX `id_person_UNIQUE` (`id_person` ASC) VISIBLE,
  INDEX `fk_person_address1_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_person_address1`
    FOREIGN KEY (`id_address`)
    REFERENCES `mydb`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `user_created` TIMESTAMP(6) NOT NULL,
  `id_address` INT NULL,
  UNIQUE INDEX `nick_UNIQUE` (`nick` ASC) VISIBLE,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_user_address1_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`id_address`)
    REFERENCES `mydb`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id_type`),
  UNIQUE INDEX `id_type_UNIQUE` (`id_type` ASC) VISIBLE,
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `flag` VARCHAR(256) NOT NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `id_human_UNIQUE` (`id_country` ASC) VISIBLE,
  UNIQUE INDEX `flag_UNIQUE` (`flag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titles` (
  `id_title` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NOT NULL,
  `id_country` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  `lenght` INT NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_title`, `id_type`),
  UNIQUE INDEX `id_titles_UNIQUE` (`id_title` ASC) VISIBLE,
  INDEX `fk_titles_type1_idx` (`id_type` ASC) VISIBLE,
  INDEX `fk_titles_country1_idx` (`id_country` ASC) VISIBLE,
  CONSTRAINT `fk_titles_type1`
    FOREIGN KEY (`id_type`)
    REFERENCES `mydb`.`type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_titles_country1`
    FOREIGN KEY (`id_country`)
    REFERENCES `mydb`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rating` (
  `id_user` INT NOT NULL,
  `id_title` INT NOT NULL,
  `rating` INT NOT NULL,
  `reason` VARCHAR(256) NULL,
  PRIMARY KEY (`id_user`, `id_title`),
  INDEX `fk_rating_titles1_idx` (`id_title` ASC) VISIBLE,
  CONSTRAINT `fk_rating_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_titles1`
    FOREIGN KEY (`id_title`)
    REFERENCES `mydb`.`titles` (`id_title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre_name` (
  `id_genre_name` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id_genre_name`),
  UNIQUE INDEX `genre_name_UNIQUE` (`genre_name` ASC) VISIBLE,
  UNIQUE INDEX `id_genre_name_UNIQUE` (`id_genre_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `id_title` INT NOT NULL,
  `id_genre_name` INT NOT NULL,
  PRIMARY KEY (`id_title`, `id_genre_name`),
  INDEX `fk_genre_genre_name1_idx` (`id_genre_name` ASC) VISIBLE,
  CONSTRAINT `fk_genre_titles1`
    FOREIGN KEY (`id_title`)
    REFERENCES `mydb`.`titles` (`id_title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_genre_name1`
    FOREIGN KEY (`id_genre_name`)
    REFERENCES `mydb`.`genre_name` (`id_genre_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favourites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favourites` (
  `id_user` INT NOT NULL,
  `id_person` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_person`),
  INDEX `fk_favourites_person1_idx` (`id_person` ASC) VISIBLE,
  CONSTRAINT `fk_favourites_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favourites_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `mydb`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role_name` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(256) NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `id_role_name_UNIQUE` (`id_role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id_title` INT NOT NULL,
  `id_person` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_title`, `id_person`, `id_role`),
  INDEX `fk_role_person1_idx` (`id_person` ASC) VISIBLE,
  INDEX `fk_role_role_name1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_role_titles1`
    FOREIGN KEY (`id_title`)
    REFERENCES `mydb`.`titles` (`id_title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_person1`
    FOREIGN KEY (`id_person`)
    REFERENCES `mydb`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_role_name1`
    FOREIGN KEY (`id_role`)
    REFERENCES `mydb`.`role_name` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
